### ISSUE TITLE
Provide a simple Maven example

### ISSUE THREAD

**Issue by pfisterer** [plison/opendial#17]
I've tried to use opendial in a Maven project. However, I could not resolve the required dependencies.

This is the pom.xml that I've used:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>test.dialog</groupId>
	<artifactId>dialog-system-demo</artifactId>
	<version>1.0-SNAPSHOT</version>
	<name>Simple Maven Project</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>

		<dependency>
			<groupId>opendial</groupId>
			<artifactId>opendial</artifactId>
			<version>1.4</version>
		</dependency>
		
	</dependencies>

	<build>
		<plugins>

			<!-- Java compiler source code version -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

		</plugins>
	</build>


	<repositories>

		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>

		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>

	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>
</project>
```

Running mvn package yields: 
```
mvn -U package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for test.dialog:dialog-system-demo:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 75, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Simple Maven Project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://jcenter.bintray.com/org/apache/maven/plugins/maven-source-plugin/maven-metadata.xml
Downloaded: http://jcenter.bintray.com/org/apache/maven/plugins/maven-source-plugin/maven-metadata.xml (808 B at 4.1 KB/sec)
Downloading: http://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.3+/httpclient-4.3+.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/httpcomponents/httpclient/4.3+/httpclient-4.3+.pom
Downloading: http://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpclient/4.3+/httpclient-4.3+.pom
[WARNING] The POM for org.apache.httpcomponents:httpclient:jar:4.3+ is missing, no dependency information available
Downloading: http://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.3+/httpmime-4.3+.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/httpcomponents/httpmime/4.3+/httpmime-4.3+.pom
Downloading: http://repo.maven.apache.org/maven2/org/apache/httpcomponents/httpmime/4.3+/httpmime-4.3+.pom
[WARNING] The POM for org.apache.httpcomponents:httpmime:jar:4.3+ is missing, no dependency information available
Downloading: http://jcenter.bintray.com/net/java/balloontip/balloontip/1.2+/balloontip-1.2+.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/net/java/balloontip/balloontip/1.2+/balloontip-1.2+.pom
Downloading: http://repo.maven.apache.org/maven2/net/java/balloontip/balloontip/1.2+/balloontip-1.2+.pom
[WARNING] The POM for net.java.balloontip:balloontip:jar:1.2+ is missing, no dependency information available
Downloading: http://jcenter.bintray.com/org/jfree/jfreechart/1.0.19+/jfreechart-1.0.19+.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/jfree/jfreechart/1.0.19+/jfreechart-1.0.19+.pom
Downloading: http://repo.maven.apache.org/maven2/org/jfree/jfreechart/1.0.19+/jfreechart-1.0.19+.pom
[WARNING] The POM for org.jfree:jfreechart:jar:1.0.19+ is missing, no dependency information available
Downloading: http://jcenter.bintray.com/de/dfki/mary/freetts/1.0/freetts-1.0.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/de/dfki/mary/freetts/1.0/freetts-1.0.pom
Downloading: http://repo.maven.apache.org/maven2/de/dfki/mary/freetts/1.0/freetts-1.0.pom
Downloading: file://${project.basedir}/../lib/repo/de/dfki/mary/freetts/1.0/freetts-1.0.pom
Downloading: http://jcenter.bintray.com/de/dfki/mary/freetts-de/1.0/freetts-de-1.0.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/de/dfki/mary/freetts-de/1.0/freetts-de-1.0.pom
Downloading: http://repo.maven.apache.org/maven2/de/dfki/mary/freetts-de/1.0/freetts-de-1.0.pom
Downloading: file://${project.basedir}/../lib/repo/de/dfki/mary/freetts-de/1.0/freetts-de-1.0.pom
Downloading: http://jcenter.bintray.com/de/dfki/mary/freetts-en_us/1.0/freetts-en_us-1.0.pom
Downloading: https://oss.sonatype.org/content/repositories/snapshots/de/dfki/mary/freetts-en_us/1.0/freetts-en_us-1.0.pom
Downloading: http://repo.maven.apache.org/maven2/de/dfki/mary/freetts-en_us/1.0/freetts-en_us-1.0.pom
[WARNING] The POM for edu.cmu.sphinx:sphinx4-core:jar:1.0-SNAPSHOT is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/jul-to-slf4j/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/slf4j/jul-to-slf4j/maven-metadata.xml
Downloading: http://jcenter.bintray.com/org/slf4j/jul-to-slf4j/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/slf4j/jul-to-slf4j/maven-metadata.xml (2 KB at 121.9 KB/sec)
Downloaded: http://jcenter.bintray.com/org/slf4j/jul-to-slf4j/maven-metadata.xml (2 KB at 14.1 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-api/maven-metadata.xml
Downloading: http://jcenter.bintray.com/org/slf4j/slf4j-api/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/maven-metadata.xml (2 KB at 165.9 KB/sec)
Downloaded: http://jcenter.bintray.com/org/slf4j/slf4j-api/maven-metadata.xml (2 KB at 22.2 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-log4j12/maven-metadata.xml
Downloading: http://jcenter.bintray.com/org/slf4j/slf4j-log4j12/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/maven-metadata.xml (3 KB at 184.7 KB/sec)
Downloaded: http://jcenter.bintray.com/org/slf4j/slf4j-log4j12/maven-metadata.xml (3 KB at 25.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.473s
[INFO] Finished at: Thu Jun 02 11:55:40 CEST 2016
[INFO] Final Memory: 8M/302M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dialog-system-demo: Could not resolve dependencies for project test.dialog:dialog-system-demo:jar:1.0-SNAPSHOT: Failed to collect dependencies at opendial:opendial:jar:1.4 -> de.dfki.mary:marytts-runtime:jar:5.1.1 -> de.dfki.mary:freetts:jar:1.0: Failed to read artifact descriptor for de.dfki.mary:freetts:jar:1.0: Could not transfer artifact de.dfki.mary:freetts:pom:1.0 from/to marytts-dependencies (file://${project.basedir}/../lib/repo): Repository path /../lib/repo does not exist, and cannot be created. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Could you provide a sample pom.xml that works?

**Comment by plison** [comment]
Thanks for the bug report. It seems that Maven has problems with the component versions with a '+' suffix (i.e. httpclient:jar:4.3+). I'll try to correct that next time I'll upload the toolkit on Bintray. 

In the meantime, I would recommend to use the versions on Github, as the one on Bintray is a bit outdated by now (last distribution there is from June 2015).

**Comment by pfisterer** [comment]
Thank you very much. Does it make sense to wait for you uploading it to Bintray? Once it works, I can provide the sample Maven project here on Github.

**Comment by plison** [comment]
Hi! I just uploaded version 1.5 of OpenDial to Bintray. Let me know if it works for you!

**Comment by pfisterer** [comment]
Hi, Thanks a million. I compiles now but I cannot execute for some reason.

Here is my demo project: https://github.com/pfisterer/opendialog-test and the output of ``` mvn exec:java -X```:
```
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /usr/local/apache-maven-3.1.1
Java version: 1.8.0, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.5", arch: "x86_64", family: "mac"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/local/apache-maven-3.1.1/conf/settings.xml
[DEBUG] Reading user settings from /Users/dp/.m2/settings.xml
[DEBUG] Using local repository at /Users/dp/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/dp/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 75, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[DEBUG] Resolving plugin version for org.apache.maven.plugins:maven-source-plugin
[DEBUG] Could not find metadata org.apache.maven.plugins:maven-source-plugin/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins:maven-source-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.apache.maven.plugins:maven-source-plugin to 3.0.0 from repository central (http://repo.maven.apache.org/maven2, releases)
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[DEBUG] Tasks:   [exec:java]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Opendial test application 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from POM de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       de.farberg.opendial:opendial-test:1.0-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [itm-maven-repository-releases (http://maven.itm.uni-luebeck.de/content/repositories/releases/, releases+snapshots), atlassian-public (https://maven.atlassian.com/repository/public, releases+snapshots), jcenter (http://jcenter.bintray.com, releases+snapshots), central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] --- init fork of de.farberg.opendial:opendial-test:1.0-SNAPSHOT for org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) ---
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] --- exit fork of de.farberg.opendial:opendial-test:1.0-SNAPSHOT for org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) ---
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <arguments>${exec.arguments}</arguments>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <cleanupDaemonThreads>${exec.cleanupDaemonThreads} default-value=</cleanupDaemonThreads>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <daemonThreadJoinTimeout default-value="15000">${exec.daemonThreadJoinTimeout}</daemonThreadJoinTimeout>
  <includePluginDependencies default-value="false">${exec.includePluginDependencies}</includePluginDependencies>
  <includeProjectDependencies default-value="true">${exec.includeProjectDependencies}</includeProjectDependencies>
  <keepAlive default-value="false">${exec.keepAlive}</keepAlive>
  <killAfter default-value="-1">${exec.killAfter}</killAfter>
  <localRepository default-value="${localRepository}"/>
  <mainClass>de.farberg.opendial.Main</mainClass>
  <pluginDependencies default-value="${plugin.artifacts}"/>
  <project default-value="${project}"/>
  <remoteRepositories default-value="${project.remoteArtifactRepositories}"/>
  <skip default-value="false">${skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <stopUnresponsiveDaemonThreads>${exec.stopUnresponsiveDaemonThreads} default-value=</stopUnresponsiveDaemonThreads>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
</configuration>
[DEBUG] =======================================================================
[INFO]
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ opendial-test >>>
[INFO]
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ opendial-test <<<
[WARNING] The POM for opendial:opendial:jar:1.5 is invalid, transitive dependencies (if any) will not be available: 2 problems were encountered while building the effective model for opendial:opendial:1.5
[ERROR] 'dependencies.dependency.groupId' for null:exp4j:jar is missing. @
[ERROR] 'dependencies.dependency.version' for null:exp4j:jar is missing. @

[DEBUG] Could not find metadata de.uniluebeck.itm.util:logging/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Skipped remote update check for de.uniluebeck.itm.util:logging/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in https://maven.atlassian.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of atlassian-public has elapsed or updates are forced
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in http://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[DEBUG] Could not find metadata de.uniluebeck.itm.util:logging/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Skipped remote update check for de.uniluebeck.itm.util:logging/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in https://maven.atlassian.com/repository/public was cached in the local repository, resolution will not be reattempted until the update interval of atlassian-public has elapsed or updates are forced
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in http://jcenter.bintray.com was cached in the local repository, resolution will not be reattempted until the update interval of jcenter has elapsed or updates are forced
[DEBUG] Failure to find de.uniluebeck.itm.util:logging/maven-metadata.xml in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[DEBUG] Could not find metadata org.slf4j:jul-to-slf4j/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Failure to find org.slf4j:jul-to-slf4j/maven-metadata.xml in http://maven.itm.uni-luebeck.de/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of itm-maven-repository-releases has elapsed or updates are forced
[DEBUG] Skipped remote update check for org.slf4j:jul-to-slf4j/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:jul-to-slf4j/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:jul-to-slf4j/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.slf4j:slf4j-api/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Failure to find org.slf4j:slf4j-api/maven-metadata.xml in http://maven.itm.uni-luebeck.de/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of itm-maven-repository-releases has elapsed or updates are forced
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.slf4j:slf4j-api/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Failure to find org.slf4j:slf4j-api/maven-metadata.xml in http://maven.itm.uni-luebeck.de/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of itm-maven-repository-releases has elapsed or updates are forced
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-api/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.slf4j:slf4j-log4j12/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Failure to find org.slf4j:slf4j-log4j12/maven-metadata.xml in http://maven.itm.uni-luebeck.de/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of itm-maven-repository-releases has elapsed or updates are forced
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.slf4j:slf4j-log4j12/maven-metadata.xml in local (/Users/dp/.m2/repository)
[DEBUG] Failure to find org.slf4j:slf4j-log4j12/maven-metadata.xml in http://maven.itm.uni-luebeck.de/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of itm-maven-repository-releases has elapsed or updates are forced
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Skipped remote update check for org.slf4j:slf4j-log4j12/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=50, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=7, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=5, ConflictResolver.conflictItemCount=29, DefaultDependencyCollector.collectTime=251, DefaultDependencyCollector.transformTime=9}
[DEBUG] de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[DEBUG]    opendial:opendial:jar:1.5:compile
[DEBUG]    de.uniluebeck.itm.util:logging:jar:RELEASE:compile
[DEBUG]       org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[DEBUG]       com.google.classpath-explorer:classpath-explorer:jar:1.0:compile
[DEBUG]    org.slf4j:slf4j-api:jar:RELEASE:compile
[DEBUG]    org.slf4j:slf4j-log4j12:jar:RELEASE:compile
[DEBUG]       log4j:log4j:jar:1.2.17:compile
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ opendial-test ---
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG] Populating class realm maven.api
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=0, ConflictMarker.nodeCount=68, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=25, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=3, ConflictResolver.conflictItemCount=65, DefaultDependencyCollector.collectTime=109, DefaultDependencyCollector.transformTime=5}
[DEBUG] org.codehaus.mojo:exec-maven-plugin:jar:1.2.1:
[DEBUG]    org.apache.maven:maven-toolchain:jar:1.0:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.0.6:compile
[DEBUG]       commons-cli:commons-cli:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.0.6:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:2.0.5:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
[DEBUG]       junit:junit:jar:3.8.2:test
[DEBUG]    org.apache.commons:commons-exec:jar:1.1:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Included: org.codehaus.mojo:exec-maven-plugin:jar:1.2.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.0.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7
[DEBUG]   Included: commons-cli:commons-cli:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:2.0.5
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.1
[DEBUG]   Excluded: org.apache.maven:maven-toolchain:jar:1.0
[DEBUG]   Excluded: org.apache.maven:maven-project:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-profile:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-registry:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact-manager:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-core:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-error-diagnostics:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-descriptor:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-monitor:jar:2.0.6
[DEBUG]   Excluded: classworlds:classworlds:jar:1.1
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:2.0.6
[DEBUG]   Excluded: org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9
[DEBUG]   Excluded: junit:junit:jar:3.8.2
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:java from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:1.2.1:java' with basic configurator -->
[DEBUG]   (f) arguments = []
[DEBUG]   (f) classpathScope = runtime
[DEBUG]   (f) cleanupDaemonThreads = false
[DEBUG]   (f) daemonThreadJoinTimeout = 15000
[DEBUG]   (f) includePluginDependencies = false
[DEBUG]   (f) includeProjectDependencies = true
[DEBUG]   (f) keepAlive = false
[DEBUG]   (f) killAfter = -1
[DEBUG]   (f) localRepository =        id: local
      url: file:///Users/dp/.m2/repository/
   layout: none

[DEBUG]   (f) mainClass = de.farberg.opendial.Main
[DEBUG]   (f) pluginDependencies = [org.codehaus.mojo:exec-maven-plugin:maven-plugin:1.2.1:, org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile, org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile, commons-cli:commons-cli:jar:1.0:compile, org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile, org.codehaus.plexus:plexus-utils:jar:2.0.5:compile, org.apache.commons:commons-exec:jar:1.1:compile]
[DEBUG]   (f) project = MavenProject: de.farberg.opendial:opendial-test:1.0-SNAPSHOT @ /Users/dp/Documents/dev/java/DHBW/opendial-test/pom.xml
[DEBUG]   (f) remoteRepositories = [       id: itm-maven-repository-releases
      url: http://maven.itm.uni-luebeck.de/content/repositories/releases/
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: atlassian-public
      url: https://maven.atlassian.com/repository/public
   layout: default
snapshots: [enabled => true, update => never]
 releases: [enabled => true, update => daily]
,        id: jcenter
      url: http://jcenter.bintray.com
   layout: default
snapshots: [enabled => true, update => never]
 releases: [enabled => true, update => daily]
,        id: central
      url: http://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG]   (f) skip = false
[DEBUG]   (f) stopUnresponsiveDaemonThreads = false
[DEBUG] -- end configuration --
[DEBUG] Invoking : de.farberg.opendial.Main.main()
[DEBUG] Plugin Dependencies will be excluded.
[DEBUG] Project Dependencies will be included.
[DEBUG] Collected project artifacts [opendial:opendial:jar:1.5:compile, de.uniluebeck.itm.util:logging:jar:0.8:compile, org.slf4j:jul-to-slf4j:jar:1.7.21:compile, com.google.classpath-explorer:classpath-explorer:jar:1.0:compile, org.slf4j:slf4j-api:jar:1.7.21:compile, org.slf4j:slf4j-log4j12:jar:1.7.21:compile, log4j:log4j:jar:1.2.17:compile]
[DEBUG] Collected project classpath [/Users/dp/Documents/dev/java/DHBW/opendial-test/target/classes]
[DEBUG] Adding to classpath : file:/Users/dp/Documents/dev/java/DHBW/opendial-test/target/classes/
[DEBUG] Adding project dependency artifact: opendial to classpath
[DEBUG] Adding project dependency artifact: logging to classpath
[DEBUG] Adding project dependency artifact: jul-to-slf4j to classpath
[DEBUG] Adding project dependency artifact: classpath-explorer to classpath
[DEBUG] Adding project dependency artifact: slf4j-api to classpath
[DEBUG] Adding project dependency artifact: slf4j-log4j12 to classpath
[DEBUG] Adding project dependency artifact: log4j to classpath
[DEBUG] joining on thread Thread[de.farberg.opendial.Main.main(),5,de.farberg.opendial.Main]
[DEBUG] Setting accessibility to true in order to invoke main().
[INFO ; Main::main] Hallo Welt!
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoClassDefFoundError: net/java/balloontip/BalloonTip
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
	at java.lang.Class.getDeclaredMethod(Class.java:2115)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6212)
	at java.awt.Component.access$500(Component.java:188)
	at java.awt.Component$3.run(Component.java:6166)
	at java.awt.Component$3.run(Component.java:6164)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6163)
	at java.awt.Component.<init>(Component.java:6132)
	at java.awt.Container.<init>(Container.java:281)
	at javax.swing.JComponent.<init>(JComponent.java:585)
	at opendial.gui.InteractionTab.<init>(InteractionTab.java:115)
	at opendial.gui.GUIFrame.start(GUIFrame.java:146)
	at opendial.DialogueSystem.startSystem(DialogueSystem.java:149)
	at opendial.DialogueSystem.main(DialogueSystem.java:893)
	at de.farberg.opendial.Main.main(Main.java:24)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.java.balloontip.BalloonTip
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
[DEBUG] joining on thread Thread[Thread-1,5,de.farberg.opendial.Main]
```

**Comment by plison** [comment]
OK, i've made some changes to the gradle configuration, it should work now - at least it works for me ;-) Could you give it a try?

I had to add the repository https://oss.sonatype.org/content/repositories/snapshots to your pom.xml file to make it work

**Comment by pfisterer** [comment]
Tnx. Can you upload a new version to bintray please?

**Comment by plison** [comment]
It is already uploaded (the version on Bintray is the last one).

**Comment by pfisterer** [comment]
Thanks a lot for your continued support. Still no luck. I've deleted my local maven cache (~/.m2/repository/) and ran ```mvn package exec:java``` and get the same result as before.

Maybe this is also an issue: ```mvn dependency:tree```yields: ```[WARNING] The POM for opendial:opendial:jar:1.5 is missing, no dependency information available```.

Full output:
```
mvn dependency:tree
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 75, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Opendial test application 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for opendial:opendial:jar:1.5 is missing, no dependency information available
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ opendial-test ---
[INFO] de.farberg.opendial:opendial-test:jar:1.0-SNAPSHOT
[INFO] +- opendial:opendial:jar:1.5:compile
[INFO] +- de.uniluebeck.itm.util:logging:jar:0.8:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile (version selected from constraint [1.7,1.8))
[INFO] |  \- com.google.classpath-explorer:classpath-explorer:jar:1.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] \- org.slf4j:slf4j-log4j12:jar:1.7.21:compile
[INFO]    \- log4j:log4j:jar:1.2.17:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.255s
[INFO] Finished at: Tue Jun 07 14:23:53 CEST 2016
[INFO] Final Memory: 12M/304M
[INFO] ------------------------------------------------------------------------
```

**Comment by plison** [comment]
Is it working for you now? I just re-uploaded the files on Bintray.

**Comment by pfisterer** [comment]
Still no luck. I've added you as a collaborator to https://github.com/pfisterer/opendialog-test/ so you can test and edit directly using this dummy project.

**Comment by plison** [comment]
I changed the repository order between atlassian and bintray  in your github project. It seems the atlassian repository is not automatically updated, and it was causing some strange dependency problems. I've now tested the setup on two different machines, and it seems to work. In case it still doesn't for you, could you send me a detailed log from maven?

**Comment by pfisterer** [comment]
Thanks a million for your support. Now it works and I get the expected output!
If you like, you can add a link to https://github.com/pfisterer/opendialog-test/ as a Maven-based example for using your project!

Best regards,
Dennis

**Comment by plison** [comment]
You're welcome ;-)
